<div id="mySideNav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>

  <div class="sub">
    <h3><?= $data['user_permission'] ?></h3>
  </div>

  <div class="sub">
    <h3>Dashboard</h3>
    <a href="/admin/dashboard" onclick="closeNav()">Dashboard</a>
  </div>


  <div class="sub">
    <h3>Customers</h3>
    <a href="/customer/list" onclick="closeNav()">Customer List</a>
  </div>

  <div class="sub">
    <h3>Inventory</h3>
    <a href="/items/list" onclick="closeNav()">Items List</a>
  </div>

  <div class="sub">
    <h3>Vendors</h3>
    <a href="/vendor/list" onclick="closeNav()">Vendor List</a>
  </div>




</div>