<div id="myTopNav" class="topnav">
  <div class="hamburger" onclick="openNav()">&#9776;</div>
  <div>
    <a href="/user/profile" class="tooltip">
      <i class="fa-solid fa-user"></i>
      <span class="tooltiptext tooltipleft">Your Profile</span>
    </a>
    <a href="/admin/user/signout" class="tooltip">
      <i class="fa-solid fa-arrow-right-from-bracket"></i>
      <span class="tooltiptext tooltipleft">Logout</span>
    </a>
  </div>
</div>