<main class="container">
  <h3>THE ADMIN USER SETUP PAGE</h3>
  <?php if (!empty($data['errorList'])) : ?>
  <div>
    <p>Requirements:</p>
    <ul>
      <?php foreach ($data['errorList'] as $value) : ?>
      <li><?= $value ?></li>
      <?php endforeach ?>
    </ul>
  </div>
  <?php endif ?>

  <form class="formBox" action="" method="post">
    <label for="email">Email</label>
    <input type="email" name="email" id="email" value="<?= $data['user_email'] ?>"
      <?= ($data['readonly']) ? 'readonly' : ''; ?> />

    <label for="permission">Permission</label>
    <input type="text" name="permission" id="permission" readonly value="super" />


    <label for="password">Password</label>
    <input type="password" name="password" id="password" <?= ($data['readonly']) ? 'readonly' : ''; ?> />


    <label for="psw_confirm">Password Confirmation</label>
    <input type="password" name="psw_confirm" id="psw_confirm" <?= ($data['readonly']) ? 'readonly' : ''; ?> />

    <?php if ($data['readonly'] == false) : ?>
    <input class="float" type="submit" value="SEND">
    <?php endif ?>
  </form>


</main>