<!DOCTYPE html>
<html lang="<?= $scMetaLanguage ?>" dir="ltr" color-scheme="auto">

<head>
  <?php include 'layout/header.basic.phtml'; ?>

  <!-- Style link to fontawesome 4 -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

  <!-- Style, Script link to SimpleMDE -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
  <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>


  <!-- <link rel="stylesheet" href="/css/admin.css"> -->
  <link rel="stylesheet" href="/css/<?= $scMetaPath; ?>.css">

</head>

<body>




  <?php include $page; ?>



  <footer>
    <?php include 'layout/footer.phtml' ?>
  </footer>




  <script src="/js/<?= $scMetaPath; ?>.js"></script>
</body>

</html>